<?php

return [
    'roles' => [
        'master_admin' => 'Master Admin',
        'dokter' => 'Dokter',
        'admin' => 'Admin',
        'admin_gudang' => 'Admin Gudang',
        'admin_apotek' => 'Admin Apotek',
        'kasir' => 'Kasir',
        'apoteker' => 'Apoteker',
        'staf_purchasing' => 'Staf Purchasing',
        'staf_dokumentasi' => 'Staf Dokumentasi',
        'owner_viewer' => 'Owner / Viewer',
        'staf' => 'Staf Lainnya',
    ],

    'permissions' => [
        'dashboard.view.global',
        'dashboard.view.own',
        'medicines.view',
        'medicines.create',
        'medicines.update',
        'medicines.delete',
        'barcode.input',
        'purchases.create',
        'purchases.update',
        'documentation.upload',
        'documentation.validate',
        'reports.view',
        'reports.export',
        'users.view',
        'users.create',
        'users.update',
        'users.reset_password',
        'users.deactivate',
        'roles_permissions.view',
        'roles_permissions.manage',
        'doctor_prescription.view',
        'doctor_prescription.create',
        'doctor_prescription.update',
        'system_settings.view',
        'system_settings.manage',
        'approvals.submit',
        'approvals.process',
        'audit_logs.view',
    ],

    'role_permissions' => [
        'master_admin' => ['*'],

        'dokter' => [
            'dashboard.view.own',
            'doctor_prescription.view',
            'doctor_prescription.create',
            'doctor_prescription.update',
            'medicines.view',
            'reports.view',
            'approvals.submit',
            'audit_logs.view',
        ],

        'admin' => [
            'dashboard.view.own',
            'medicines.view',
            'medicines.create',
            'medicines.update',
            'medicines.delete',
            'barcode.input',
            'purchases.create',
            'purchases.update',
            'documentation.upload',
            'documentation.validate',
            'reports.view',
            'reports.export',
            'approvals.submit',
            'audit_logs.view',
        ],

        'admin_gudang' => [
            'dashboard.view.own',
            'medicines.view',
            'medicines.update',
            'barcode.input',
            'purchases.create',
            'purchases.update',
            'documentation.upload',
            'reports.view',
            'approvals.submit',
            'audit_logs.view',
        ],

        'admin_apotek' => [
            'dashboard.view.own',
            'medicines.view',
            'medicines.create',
            'medicines.update',
            'barcode.input',
            'documentation.validate',
            'reports.view',
            'reports.export',
            'approvals.submit',
            'audit_logs.view',
        ],

        'kasir' => [
            'dashboard.view.own',
            'medicines.view',
            'doctor_prescription.view',
            'reports.view',
            'approvals.submit',
            'audit_logs.view',
        ],

        'apoteker' => [
            'dashboard.view.own',
            'medicines.view',
            'medicines.update',
            'doctor_prescription.view',
            'doctor_prescription.update',
            'reports.view',
            'documentation.validate',
            'approvals.submit',
            'audit_logs.view',
        ],

        'staf_purchasing' => [
            'dashboard.view.own',
            'purchases.create',
            'reports.view',
            'approvals.submit',
            'audit_logs.view',
        ],

        'staf_dokumentasi' => [
            'dashboard.view.own',
            'documentation.upload',
            'reports.view',
            'approvals.submit',
            'audit_logs.view',
        ],

        'owner_viewer' => [
            'dashboard.view.global',
            'medicines.view',
            'reports.view',
            'reports.export',
            'audit_logs.view',
        ],

        'staf' => [
            'dashboard.view.own',
            'reports.view',
            'approvals.submit',
        ],
    ],
];
